# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYXxpspC28FwHyjQAcnoAmmLpcGvEePX
"""

!pip install streamlit langchain google-generativeai requests beautifulsoup4

import os

os.makedirs("tools", exist_ok=True)

# create job_search.py file with the search_jobs function
with open("tools/job_search.py", "w") as f:
    f.write("""
import requests
from bs4 import BeautifulSoup

def search_jobs(role):
    \"\"\"
    Searches for job postings based on the specified role.
    This is a placeholder function and uses a simplified scraping approach.
    For a real application, consider using job board APIs or more robust scraping techniques.
    \"\"\"
    # Example: Searching on a hypothetical job board
    search_url = f"https://www.indeed.com/jobs?q={role.replace(' ', '+')}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    try:
        response = requests.get(search_url, headers=headers)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        soup = BeautifulSoup(response.text, 'html.parser')

        job_listings = []
        # This is a very basic example, actual scraping would require inspecting the website's HTML structure.
        # Let's simulate some job data based on the role.
        if 'engineer' in role.lower():
            job_listings.append(f"Software Engineer at TechCorp - {role}")
            job_listings.append(f"Senior {role} at InnovateX")
        elif 'analyst' in role.lower():
            job_listings.append(f"Data Analyst at Analytics Inc. - {role}")
            job_listings.append(f"Business Analyst at Global Solutions")
        else:
            job_listings.append(f"Junior {role} at StartupZ")
            job_listings.append(f"Experienced {role} position available")

        if not job_listings:
            return ["No jobs found for the specified role."]

        return job_listings
    except requests.exceptions.RequestException as e:
        return [f"Error searching for jobs: {e}"]

""")

print("Project structure created ✅")

!pip install openai

!pip install google-generativeai

!pip install openai

!pip install google-generativeai

!pip install -q google-genai

from google import genai
import importlib

# Reload the module to ensure the latest changes are picked up
import tools.job_search
importlib.reload(tools.job_search)
from tools.job_search import search_jobs

# Initialize Gemini client
client = genai.Client(api_key="AIzaSyCI6j-XvJCUnxsy8OIhhs-NjgIkgx2N8O0")


def job_agent(user_query):
    """
    Agent extracts job role and searches jobs
    """

    try:
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=f"Extract the job role from this request: {user_query}. Return only the role."
        )

        role = response.text.strip()

    except:
        # fallback if Gemini quota/API fails
        role = user_query

    jobs = search_jobs(role)

    return jobs

import os

os.makedirs("tools", exist_ok=True)

from google import genai
from tools.job_search import search_jobs

# Initialize Gemini client
client = genai.Client(api_key="AIzaSyCI6j-XvJCUnxsy8OIhhs-NjgIkgx2N8O0")


def job_agent(user_query):

    # Ask Gemini to extract the job role
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=f"Extract the job role from this request: {user_query}"
    )

    role = response.text.strip()

    jobs = search_jobs(role)

    return jobs