# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kTubVoxYL_Rpdcj-fDzwrUTZ29NQC0q
"""

!pip install streamlit langchain google-generativeai requests beautifulsoup4

import os

os.makedirs("tools", exist_ok=True)

# create empty job_search.py file
with open("tools/job_search.py", "w") as f:
    f.write("")

print("Project structure created ✅")

from openai import OpenAI

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="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"
)

response = client.chat.completions.create(
    model="openai/gpt-4o-mini",
    messages=[
        {"role": "user", "content": "Hello"}
    ]
)

print(response.choices[0].message.content)

!pip install gradio openai

"""!pip install langchain langchain-community langchain-openai"""

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

import os
os.environ["OPENAI_API_KEY"] = "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"

llm = ChatOpenAI(model="openai/gpt-4o-mini", openai_api_base="https://openrouter.ai/api/v1")

messages = [
    SystemMessage(content="You are a helpful assistant."),
    HumanMessage(content="What is Python?")
]

response = llm.invoke(messages)

print(response.content)

import gradio as gr
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

# Connect AI using LangChain
llm = ChatOpenAI(
    model="openai/gpt-4o-mini",
    openai_api_base="https://openrouter.ai/api/v1",
    api_key="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"
)

# Career suggestion function
def career_bot(message, history):

    messages = [
        SystemMessage(content="You are an AI career advisor. Based on the user's interests, skills, and favorite subjects, suggest 3-5 careers from ANY field like technology, medicine, law, finance, business, design, education, or engineering."),
        HumanMessage(content=message)
    ]

    response = llm.invoke(messages)

    return response.content


# Create chat interface
chatbot = gr.ChatInterface(
    fn=career_bot,
    title="AI Career Guidance Chatbot",
    description="Tell me your interests, skills, or favorite subjects and I will suggest careers."
)

chatbot.launch()

import requests

def search_jobs(query):

    url = "https://remotive.com/api/remote-jobs"

    response = requests.get(url)
    data = response.json()

    jobs = data["jobs"]

    results = []

    for job in jobs:
        if query.lower() in job["title"].lower():
            results.append({
                "title": job["title"],
                "company": job["company_name"],
                "location": job["candidate_required_location"],
                "url": job["url"]
            })

    return results[:5]

jobs = search_jobs("python")

for job in jobs:
    print("Title:", job["title"])
    print("Company:", job["company"])
    print("Location:", job["location"])
    print("Apply:", job["url"])
    print()

from langchain_core.messages import HumanMessage, SystemMessage

def job_agent(user_query):

    messages = [
        SystemMessage(content="Extract the job role from the user's request."),
        HumanMessage(content=user_query)
    ]

    response = llm.invoke(messages)

    role = response.content.strip()

    print("Agent decided to search for:", role)
    print()

    jobs = search_jobs(role)

    for job in jobs:
        print("Title:", job["title"])
        print("Company:", job["company"])
        print("Location:", job["location"])
        print("Apply:", job["url"])
        print()

def search_jobs(query):

    url = "https://remotive.com/api/remote-jobs"

    response = requests.get(url)
    data = response.json()

    jobs = data["jobs"]

    results = []

    query = query.lower()

    for job in jobs:
        title = job["title"].lower()

        if query in title or "python" in title:

            results.append({
                "title": job["title"],
                "company": job["company_name"],
                "location": job["candidate_required_location"],
                "url": job["url"]
            })

    return results[:5]

job_agent("Find python developer jobs")