# -*- coding: utf-8 -*-
"""AGENT (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWxsoxc8lXbROyxBZ_3yAgpsPF2MG7-I
"""

!pip install streamlit pyngrok google-genai requests

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from agent import job_agent
# 
# st.title("AI Job Search Assistant")
# 
# query = st.text_input("Enter job role (example: python developer)")
# 
# if st.button("Search Jobs"):
# 
#     jobs = job_agent(query)
# 
#     if not jobs:
#         st.write("No jobs found")
# 
#     else:
#         for job in jobs:
#             st.subheader(job["title"])
#             st.write("Company:", job["company"])
#             st.write("Location:", job["location"])
#             st.write("Apply:", job["url"])
#             st.write("---")

!streamlit run app.py &>/dev/null &

!ngrok config add-authtoken 3AXWdLYFp21qNmp7Va6dBB4ZRoC_35rWntc9adaGaNCuBr9GZ

!streamlit run app.py &>/dev/null &

!killall ngrok
!killall streamlit

!streamlit run app.py &>/dev/null &

"""# Task
Terminate all existing `ngrok` processes and then connect a new `ngrok` tunnel to expose the Streamlit application running on port 8501.

## Terminate Ngrok Processes Forcefully

### Subtask:
Terminate all ngrok related processes to ensure no conflicts when starting a new tunnel.

**Reasoning**:
The subtask requires terminating all ngrok processes to prevent conflicts. The instruction explicitly states to use `!pkill -f ngrok` for this purpose.
"""

!pkill -f ngrok
print("Attempted to terminate all ngrok processes.")

"""## Connect Ngrok Tunnel

### Subtask:
Attempt to establish a new `ngrok` tunnel to expose the Streamlit application.

## Summary:

### Data Analysis Key Findings
- The command `pkill -f ngrok` was executed to forcefully terminate any running `ngrok` processes.
- The execution of the termination command was confirmed by the message: "Attempted to terminate all ngrok processes."
- No errors were reported during the termination process, indicating a successful attempt to clear existing `ngrok` instances.

### Insights or Next Steps
- Successfully terminating existing `ngrok` processes is a crucial prerequisite for establishing a new, clean `ngrok` tunnel without conflicts.

# Task
Connect a new ngrok tunnel to expose the Streamlit application.

## Terminate Ngrok Processes Forcefully

### Subtask:
Increase the delay after forcefully terminating `streamlit` and `ngrok` processes to allow the `ngrok` cloud service sufficient time to release the endpoint.

**Reasoning**:
The subtask requires increasing the delay after terminating Streamlit and ngrok processes. This code block combines all the necessary commands, including importing `time`, forcefully killing `streamlit` and `ngrok` processes, calling `ngrok.kill()`, and then introducing a 30-second delay.
"""

import time

!killall -9 streamlit
!pkill -f ngrok
from pyngrok import ngrok

ngrok.kill()
time.sleep(30) # Increased delay to ensure ngrok releases the endpoint
print("Streamlit and ngrok processes terminated, and a 30-second delay introduced.")

"""## Connect Ngrok Tunnel

### Subtask:
Attempt to establish a new ngrok tunnel after the extended delay to expose the Streamlit application.

## Summary:

### Data Analysis Key Findings
*   The `streamlit` process was not running when the termination command (`killall -9 streamlit`) was executed.
*   `ngrok` processes were successfully terminated using `pkill -f ngrok` and `ngrok.kill()`.
*   A 30-second delay was implemented after process termination to ensure the `ngrok` cloud service had sufficient time to release endpoints.

### Insights or Next Steps
*   The increased 30-second delay after terminating `streamlit` and `ngrok` processes is a critical step to prevent conflicts and ensure a clean state for establishing a new `ngrok` tunnel.
*   The next logical step is to attempt to establish the new `ngrok` tunnel, as the environment has been prepared by ensuring all previous related processes are terminated and endpoints are likely released.
"""

!mkdir -p tools

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tools/job_search.py
# def search_jobs(role_title: str) -> list:
#     """
#     Searches for open job postings.
#     Returns a list of dictionaries containing job details.
#     """
#     print(f"🔧 Tool Execution: Searching for {role_title} jobs...")
# 
#     # Mock API response formatted for your Streamlit UI
#     return [
#         {
#             "title": f"Senior {role_title.title()}",
#             "company": "Tech Innovators Inc.",
#             "location": "Remote",
#             "url": "https://example.com/apply/1"
#         },
#         {
#             "title": f"{role_title.title()} II",
#             "company": "DataCorp Solutions",
#             "location": "New York, NY",
#             "url": "https://example.com/apply/2"
#         }
#     ]

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tools/company_research.py
# def research_company(company_name: str) -> str:
#     """
#     Gathers background information on a specific company.
#     """
#     print(f"🔧 Tool Execution: Researching {company_name}...")
# 
#     # Mock company database/search response
#     company_database = {
#         "Tech Innovators Inc.": "A fast-growing startup known for its great work-life balance and AI products.",
#         "DataCorp Solutions": "An established enterprise data firm with excellent healthcare benefits."
#     }
# 
#     return company_database.get(company_name, "A solid company in its industry.")

from tools.job_search import search_jobs
from tools.company_research import research_company

# 1. Install necessary libraries (just in case your Colab runtime restarted)
!pip install streamlit pyngrok google-genai -q

# 2. Add your NEW ngrok token here
!ngrok config add-authtoken YOUR_NEW_NGROK_TOKEN

import time
import subprocess
from pyngrok import ngrok

# 3. Terminate any old processes so they don't block the port
!killall -9 streamlit
!pkill -f ngrok
time.sleep(2)

# 4. Start the Streamlit app in the background
print("Starting Streamlit server...")
subprocess.Popen(["streamlit", "run", "app.py"])

# Give Streamlit a few seconds to fully boot up
time.sleep(5)

# 5. Connect the ngrok tunnel to port 8501 (Streamlit's default port)
public_url = ngrok.connect(8501)
print(f"🚀 Your AI Job Agent is live! Click this link to open it: {public_url}")

# 1. Install necessary libraries (just in case your Colab runtime restarted)
!pip install streamlit pyngrok google-genai -q

# 2. Add your NEW ngrok token here
!ngrok config add-authtoken YOUR_NEW_NGROK_TOKEN

import time
import subprocess
from pyngrok import ngrok

# 3. Terminate any old processes so they don't block the port
!killall -9 streamlit
!pkill -f ngrok
time.sleep(2)

# 4. Start the Streamlit app in the background
print("Starting Streamlit server...")
subprocess.Popen(["streamlit", "run", "app.py"])

# Give Streamlit a few seconds to fully boot up
time.sleep(5)

# 5. Connect the ngrok tunnel to port 8501 (Streamlit's default port)
public_url = ngrok.connect(8501)
print(f"🚀 Your AI Job Agent is live! Click this link to open it: {public_url}")