# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TlAWXMqDeG89bHGZOEVd1tUI1_cqZ_F5
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import requests
# 
# # Job search function
# def search_jobs(query):
# 
#     url = "https://remotive.com/api/remote-jobs"
#     response = requests.get(url)
#     data = response.json()
# 
#     jobs = data["jobs"]
# 
#     results = []
#     query = query.lower()
# 
#     for job in jobs:
# 
#         title = job["title"].lower()
# 
#         # better matching
#         if query in title or "python" in title:
# 
#             results.append({
#                 "title": job["title"],
#                 "company": job["company_name"],
#                 "location": job["candidate_required_location"],
#                 "url": job["url"]
#             })
# 
#     return results[:5]
# 
# 
# # Streamlit UI
# st.title("AI Job Search Assistant")
# 
# query = st.text_input("Enter job role (example: python developer)")
# 
# if st.button("Search Jobs"):
# 
#     jobs = search_jobs(query)
# 
#     if not jobs:
#         st.write("No jobs found")
# 
#     else:
#         for job in jobs:
#             st.subheader(job["title"])
#             st.write("Company:", job["company"])
#             st.write("Location:", job["location"])
#             st.write("Apply:", job["url"])
#             st.write("---")

!streamlit run app.py &>/dev/null &

!ngrok config add-authtoken 3AXWdLYFp21qNmp7Va6dBB4ZRoC_35rWntc9adaGaNCuBr9GZ

!streamlit run app.py &>/dev/null &

from pyngrok import ngrok
print(ngrok.connect(8501))